title: charczuk.com
author: Will Charczuk

outputPath: dist
postsPath: posts
postTemplate: layout/post.html
pagesPath: layout/pages
partialsPath: layout/partials

s3:
  region: us-east-1
  bucket: www.charczuk.com
