posted: 2019-04-20T17:40:48-04:00
title: Skating in the Park
location: Washington Square Park, New York, NY
tags:
  - monochrome
  - skateboarder
  - street-photography
  - canon
  - digital
  - new york
