posted: 2018-11-08T00:12:18-08:00
title: Under Canvas
location: Under Canvas Zion, Springdale, UT
tags:
  - under canvas
  - tent
  - long-exposure
  - portfolio
  - travel
  - digital
  - color
  - canon
