posted: 2019-11-28T18:26:53-08:00
title: Skateboarder in Japantown
location: San Francisco, CA
tags:
  - film
  - 35mm
  - leica-m6
  - leica
  - skateboarder
  - kodak-400tx
  - monochrome
  - street-photography
  - portfolio
