posted: 2018-02-16T19:13:26-08:00
title: Chinatown Fireworks
location: Chinatown, San Francisco, CA
tags:
  - san francisco
  - chinatown
  - fireworks
  - documentary
  - street-photography
  - canon
  - digital
  - color
