posted: 2019-01-02T16:16:27-08:00
title: Chinatown Noodles
location: Chinatown, San Francisco, CA
tags:
  - chinatown
  - san francisco
  - street-photography
  - fuji
  - digital
  - color
  - documentary
