name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v4
      with:
        repository: "wcharczuk/go"
        path: "../go.charczuk.com"

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install Blogctl
      run: go install go.charczuk.com/project/blogctl@latest
      working-directory: "../go.charczuk.com"

    - name: Build
      run: blogctl build

    - name: Deploy
      run: blogctl deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
